export const theme = {
  color: {
    primary: {
      main: "#61cbe9",
      dark: "#CA5804",
      light: "#ffffff",
      lighter: "#FABB8C",
      contrastText: "#fff",
      text: "#000000",
    },
    secondary: {
      main: "#fff",
      dark: "#fff",
      light: "#fff",
      lighter: "#9A9A9A",
      contrastText: "#61cbe9",
      text: "#000000",
    },
    terciary: {
      main: "#F3F3F3",
      dark: "#DDDDDD",
      light: "#F6F6F6",
      lighter: "#F9F9F9",
      contrastText: "#212121",
      text: "#000000",
    },
    error: {
      main: "#FF2D55",
      dark: "#D12546",
      light: "#FF5373",
      lighter: "#FF728C",
      contrastText: "#fff",
    },
    warning: {
      main: "#FFCC00",
      dark: "#D1A700",
      light: "#FFD52E",
      lighter: "#FFDC54",
      contrastText: "#212121",
    },
    info: {
      main: "#007AFF",
      dark: "#0064D1",
      light: "#2E92FF",
      lighter: "#54A5FF",
      contrastText: "#fff",
    },
    success: {
      main: "#4CD964",
      dark: "#3FB252",
      light: "#6CDF80",
      lighter: "#86E497",
      contrastText: "#fff",
    },
    disabled: {
      main: "#adabab",
      dark: "#0a050b",
      light: "#ffffff",
      lighter: "#5d5d5d",
      contrastText: "#212121",
    },
    container: {
      mainCard: "#61cbe9",
      secondayCard: "#f7f7f7",
      terciaryCard: "#fff",
      mainPage: "#61cbe9",
      secondayPage: "#f7f7f7",
      terciaryPage: "#fff",
      mainColor: "#000000",
      secondayColor: "#000",
      terciaryColor: "#0a050b",
    },
    colorText: {
      leyend: "#000",
      body: "#000",
      subtitle: "#f7f7f7",
      title: "#000",
      titleExtra: "#000",
      message: "#000",
    },
  },
  font: {
    fontFamily: {
      font1: "roboto",
      font2: "Segoe UI",
      font3: "Helvetica Neue",
      font4: "Arial",
      font5: "sans-serif",
    },
    fontSize: {
      leyend: "0.75rem",
      body: "5vw",
      subtitle: "4.44vw",
      title: "5vw",
      titleExtra: "1.875rem",
      message: "3.05vw",
    },
    fontAlign: {
      right: "right",
      left: "left",
      center: "center",
    },
  },
  boxShadow: {
    shadow0: "none",
    shadow1:
      "0px 2px 1px -1px rgba(0,0,0,0.2),0px 1px 1px 0px rgba(0,0,0,0.14),0px 1px 3px 0px rgba(0,0,0,0.12)",
    shadow2:
      "0px 3px 1px -2px rgba(0,0,0,0.2),0px 2px 2px 0px rgba(0,0,0,0.14),0px 1px 5px 0px rgba(0,0,0,0.12)",
  },
  radius: {
    boxRadius0: "0px",
    boxRadius1: "4px",
    boxRadius2: "8px",
    boxRadius3: "16px",
    boxRadius4: "32px",
  },
};
